/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DemoRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'getAllDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], []),
  'getMyDemoRequest' : IDL.Func([], [IDL.Opt(DemoRequest)], ['query']),
  'hasDemoRequest' : IDL.Func([], [IDL.Bool], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeMyDemoRequest' : IDL.Func([], [], []),
  'removeSelfAsAdmin' : IDL.Func([], [], []),
  'submitDemoRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DemoRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'getAllDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], []),
    'getMyDemoRequest' : IDL.Func([], [IDL.Opt(DemoRequest)], ['query']),
    'hasDemoRequest' : IDL.Func([], [IDL.Bool], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeMyDemoRequest' : IDL.Func([], [], []),
    'removeSelfAsAdmin' : IDL.Func([], [], []),
    'submitDemoRequest' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };