/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DemoRequest {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface _SERVICE {
  /**
   * / Add a new admin (admin only).
   */
  'addAdmin' : ActorMethod<[Principal], boolean>,
  /**
   * / Get all demo requests (admin only).
   */
  'getAllDemoRequests' : ActorMethod<[], Array<DemoRequest>>,
  /**
   * / Get your own demo request.
   */
  'getMyDemoRequest' : ActorMethod<[], [] | [DemoRequest]>,
  /**
   * / Check if the caller has an existing demo request.
   */
  'hasDemoRequest' : ActorMethod<[], boolean>,
  /**
   * / Initialize the canister (first admin).
   */
  'initialize' : ActorMethod<[], undefined>,
  /**
   * / Check if the caller is an admin.
   */
  'isAdmin' : ActorMethod<[], boolean>,
  /**
   * / Remove your demo request.
   */
  'removeMyDemoRequest' : ActorMethod<[], undefined>,
  /**
   * / Remove yourself from admins.
   */
  'removeSelfAsAdmin' : ActorMethod<[], undefined>,
  /**
   * / Submit a new demo request.
   */
  'submitDemoRequest' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];